export const DATA = [
	{
		id: 1,
		author: "user name 1",
		text: "password 1",
		source: "link to ",
		tags: ["tag1"],
		createdBy: "Author1",
		createdAt: 2012,
		updatedAt: 2021,
		isDeleted: false,
	},
	{
		id: 2,
		author: "user name 2",
		text: "password 2",
		source: "link to ",
		tags: ["tag1"],
		createdBy: "Author2",
		createdAt: 2012,
		updatedAt: 2021,
		isDeleted: false,
	},
	{
		id: 3,
		author: "user name 3",
		text: "password 3",
		source: "link to ",
		tags: ["tag3"],
		createdBy: "Author3",
		createdAt: 2012,
		updatedAt: 2021,
		isDeleted: false,
	},
];
